Lindley <- R6Class("Lindley",
                   inherit=ContinuousDistribution,
                   public=list(names=c("theta"),
                               theta=NA,
                               initialize=function(theta=1) { self$theta <- theta },
                               supp=function() { c(0, Inf) },
                               properties=function() { list() },
                               pdf=function(x, log=FALSE) { new.dist::dLd(x, self$theta, log=log) },
                               cdf=function(x) { new.dist::pLd(x, self$theta) },
                               quan=function(x) { new.dist::qLd(x, self$theta) }))
